# Import libraries

In [1]:
# ! pip install faker

In [1]:
import panda as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta
import uuid

from random import randint, uniform
from faker.providers import BaseProvider

ModuleNotFoundError: No module named 'panda'

In [3]:
fake = Faker()
start_date = datetime.strptime("2005-01-01", "%Y-%m-%d")
end_date = datetime.strptime("2023-12-31", "%Y-%m-%d")

In [4]:
def generate_random_id():
    return(uuid.uuid1().hex)

# Data generation

## Tables Customer data

In [2]:
from random import randint, uniform
from faker.providers import BaseProvider

import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta
import uuid

from random import randint, uniform
from faker.providers import BaseProvider


def generate_randoms_id():
    return(uuid.uuid1().hex)

fake = Faker()
start_date = datetime.strptime("2005-01-01", "%Y-%m-%d")
end_date = datetime.strptime("2023-12-31", "%Y-%m-%d")

class CameroonPhoneProvider(BaseProvider):
    def phone_number(self):
        """Generates a fake Cameroon phone number in a random format."""
        formats = [
            "+237 65ABCDEFG",
            "+237 67ABCDEFG",
            "+237 68ABCDEFG",
            "+237 69ABCDEFG",
        ]
        format_str = formats[randint(0, len(formats) - 1)]
        phone_number = format_str.replace("A", str(randint(0, 9)))
        phone_number = phone_number.replace("B", str(randint(0, 9)))
        phone_number = phone_number.replace("C", str(randint(0, 9)))
        phone_number = phone_number.replace("D", str(randint(0, 9)))
        phone_number = phone_number.replace("E", str(randint(0, 9)))
        phone_number = phone_number.replace("F", str(randint(0, 9)))
        phone_number = phone_number.replace("G", str(randint(0, 9)))
        return phone_number

fake = Faker()
fake.add_provider(CameroonPhoneProvider)

cam_phone_number = fake.phone_number()
print(cam_phone_number)

ModuleNotFoundError: No module named 'panda'

In [6]:
customers_list = []
for i in range(10000):
    first_name = fake.first_name()
    last_name = fake.last_name()
    domain = fake.domain_name()
    email = f"{first_name}.{last_name}@{domain}"
    phone_number = cam_phone_number
    registration_date = fake.date_between(start_date, end_date)
    date_of_birth = fake.date_of_birth(minimum_age=30, maximum_age=75)
    address = fake.address()
    city = random.choice(["Yaound√©", "Douala", "Bafoussam", "Dschang", "Garoua", "Maroua", "Bamenda", "Ngaound√©r√©", "Nkongsamba", "Limbe", "Bertoua", "Mbouda", "Guider","Foumban", "Tibati", "Buea", "Kumba", "Kribi", "Loum", "Nkambe","Bangangt√©", "Baham", "Ndikinim√©ki", "Wum", "Batouri", "Yokadouma", "Mindif", "Meigang", "Abong-Mbang", "Bertoua", "Bogo", "Dir", "Poli", "Mbouda", "Bakoum", "Ngaoundal", "Figuil", "Mayo-Darl√©", "Mayo-Rey", "Betar√©-Oya", "Guidiguis", "Minjibir", "Mbankomo", "Ntui", "Mengang", "Akonolinga", "Ebolowa", "Ab√©", "Sangm√©lima", "Oveng", "Bipindi", "Meyomess√©",])
    region = random.choice(["Nord", "Sud", "Est", "Ouest", "Centre", "Littoral", "Adamaoua", "Nord-ouest", "Sud-ouest", "Extr√®me-nord"])

    date_dict = {
        'customer_id' :generate_random_id(), 
        'first_name': first_name, 
        'last_name': last_name,
        'email': email,
        'phone_number': phone_number,
        'registration_date': registration_date,
        'date_of_birth' : date_of_birth,
        'address': address,
        'city': city,
        'region' : region
        }
    customers_list.append(date_dict)
customer_df = pd.DataFrame(customers_list)
print(customer_df.shape)
customer_df.head()

(10000, 10)

,customer_id,first_name,last_name,email,phone_number,registration_date,date_of_birth,address,city,region
0,cb135c193e5011ef80669cb6d0da64b6,Laura,Delgado,Laura.Delgado@douglas.net,+237 654588596,2021-03-01,1970-12-05,"9419 William Parkways\nPort Jamesberg, AL 08961",Maroua,Ouest
1,cb13bec43e5011efbce89cb6d0da64b6,Sandra,West,Sandra.West@palmer.com,+237 654588596,2013-07-12,1973-02-04,"39986 Brian Shoal\nRandyfurt, WV 48181",Ntui,Ouest
2,cb140cee3e5011ef8b749cb6d0da64b6,Debbie,Moore,Debbie.Moore@lee-hall.com,+237 654588596,2021-04-16,1982-10-13,"01691 Miller Shore\nWilkersonside, IL 61156",Bangangt√©,Est
3,cb14823e3e5011ef93bd9cb6d0da64b6,Janet,Hinton,Janet.Hinton@barnes.com,+237 654588596,2014-09-19,1950-05-18,"9161 Martin Drives\nChristopherfort, MA 11603",Limbe,Sud-ouest
4,cb14d0423e5011ef9b849cb6d0da64b6,Fred,Proctor,Fred.Proctor@richardson-berry.info,+237 654588596,2019-08-05,1955-08-03,"PSC 1302, Box 7660\nAPO AE 13013",Bogo,Ouest

In [7]:
customer_df.to_csv('../tables/customers.csv')

## Device data

In [8]:
device_id_list = [generate_random_id() for i in range(200)]
device_id_list

['d5f4a18a3e5011ef8cb39cb6d0da64b6',
 'd5f4a18b3e5011efbc889cb6d0da64b6',
 'd5f4a18c3e5011efb4919cb6d0da64b6',
 'd5f4a18d3e5011efb9229cb6d0da64b6',
 'd5f4a18e3e5011ef9ec89cb6d0da64b6',
 'd5f4a18f3e5011efb68b9cb6d0da64b6',
 'd5f4a1903e5011ef8c9f9cb6d0da64b6',
 'd5f4a1913e5011ef8c379cb6d0da64b6',
 'd5f4a1923e5011ef8df19cb6d0da64b6',
 'd5f4a1933e5011ef9cc39cb6d0da64b6',
 'd5f4a1943e5011efaee79cb6d0da64b6',
 'd5f4c8863e5011ef801a9cb6d0da64b6',
 'd5f4c8873e5011efb8a19cb6d0da64b6',
 'd5f4c8883e5011ef805e9cb6d0da64b6',
 'd5f4c8893e5011ef997d9cb6d0da64b6',
 'd5f4c88a3e5011efaa139cb6d0da64b6',
 'd5f4c88b3e5011ef90209cb6d0da64b6',
 'd5f4c88c3e5011efa8ef9cb6d0da64b6',
 'd5f4c88d3e5011efacd19cb6d0da64b6',
 'd5f4c88e3e5011efb43f9cb6d0da64b6',
 'd5f4c88f3e5011efb08d9cb6d0da64b6',
 'd5f4c8903e5011efa39c9cb6d0da64b6',
 'd5f4c8913e5011efa0ed9cb6d0da64b6',
 'd5f4c8923e5011efa8619cb6d0da64b6',
 'd5f4c8933e5011efb44d9cb6d0da64b6',
 'd5f4c8943e5011efac2a9cb6d0da64b6',
 'd5f4c8953e5011ef8ec59cb6d0da64b6',
 'd5f4c8963e5011ef90fb9cb6d0da64b6',
 'd5f4c8973e5011efaa029cb6d0da64b6',
 'd5f4c8983e5011efbbf79cb6d0da64b6',
 'd5f4c8993e5011ef92229cb6d0da64b6',
 'd5f4c89a3e5011ef82159cb6d0da64b6',
 'd5f4c89b3e5011efa2fc9cb6d0da64b6',
 'd5f4c89c3e5011ef81da9cb6d0da64b6',
 'd5f4c89d3e5011ef95399cb6d0da64b6',
 'd5f4c89e3e5011ef8c849cb6d0da64b6',
 'd5f4c89f3e5011ef86769cb6d0da64b6',
 'd5f4c8a03e5011efbf899cb6d0da64b6',
 'd5f4c8a13e5011ef9e679cb6d0da64b6',
 'd5f4c8a23e5011efb3be9cb6d0da64b6',
 'd5f4c8a33e5011ef8d3d9cb6d0da64b6',
 'd5f4c8a43e5011efb9ed9cb6d0da64b6',
 'd5f4c8a53e5011ef9a029cb6d0da64b6',
 'd5f4c8a63e5011efabda9cb6d0da64b6',
 'd5f4c8a73e5011ef9bf29cb6d0da64b6',
 'd5f4c8a83e5011efa9f99cb6d0da64b6',
 'd5f4c8a93e5011ef89a39cb6d0da64b6',
 'd5f4c8aa3e5011ef9b1d9cb6d0da64b6',
 'd5f4c8ab3e5011ef837a9cb6d0da64b6',
 'd5f4c8ac3e5011ef870d9cb6d0da64b6',
 'd5f4c8ad3e5011ef960c9cb6d0da64b6',
 'd5f4c8ae3e5011efa4d29cb6d0da64b6',
 'd5f4c8af3e5011efb8e79cb6d0da64b6',
 'd5f4c8b03e5011efb3ad9cb6d0da64b6',
 'd5f4c8b13e5011ef81079cb6d0da64b6',
 'd5f4c8b23e5011ef9cc69cb6d0da64b6',
 'd5f4c8b33e5011ef90de9cb6d0da64b6',
 'd5f4c8b43e5011ef93819cb6d0da64b6',
 'd5f4c8b53e5011ef9cb89cb6d0da64b6',
 'd5f4c8b63e5011ef9bac9cb6d0da64b6',
 'd5f4c8b73e5011efb78b9cb6d0da64b6',
 'd5f4c8b83e5011efa6139cb6d0da64b6',
 'd5f4c8b93e5011ef8e779cb6d0da64b6',
 'd5f4c8ba3e5011efb7eb9cb6d0da64b6',
 'd5f4c8bb3e5011efa82f9cb6d0da64b6',
 'd5f4c8bc3e5011efb00d9cb6d0da64b6',
 'd5f4c8bd3e5011efaebc9cb6d0da64b6',
 'd5f4c8be3e5011ef8a449cb6d0da64b6',
 'd5f4c8bf3e5011efb6b99cb6d0da64b6',
 'd5f4c8c03e5011ef80769cb6d0da64b6',
 'd5f4c8c13e5011ef9da99cb6d0da64b6',
 'd5f4c8c23e5011efafaa9cb6d0da64b6',
 'd5f4c8c33e5011efb6ad9cb6d0da64b6',
 'd5f4c8c43e5011efb4b99cb6d0da64b6',
 'd5f4c8c53e5011efb48a9cb6d0da64b6',
 'd5f4c8c63e5011efb2be9cb6d0da64b6',
 'd5f4c8c73e5011ef881a9cb6d0da64b6',
 'd5f4c8c83e5011ef94b29cb6d0da64b6',
 'd5f4c8c93e5011efa01d9cb6d0da64b6',
 'd5f4c8ca3e5011ef9f0a9cb6d0da64b6',
 'd5f4c8cb3e5011ef8e4f9cb6d0da64b6',
 'd5f4ef813e5011ef9dd69cb6d0da64b6',
 'd5f4ef823e5011ef954b9cb6d0da64b6',
 'd5f4ef833e5011ef9cdc9cb6d0da64b6',
 'd5f4ef843e5011efaf669cb6d0da64b6',
 'd5f4ef853e5011efbf419cb6d0da64b6',
 'd5f4ef863e5011ef92549cb6d0da64b6',
 'd5f4ef873e5011efae329cb6d0da64b6',
 'd5f4ef883e5011ef962f9cb6d0da64b6',
 'd5f4ef893e5011efa8949cb6d0da64b6',
 'd5f4ef8a3e5011ef95719cb6d0da64b6',
 'd5f4ef8b3e5011efbb699cb6d0da64b6',
 'd5f4ef8c3e5011ef87d89cb6d0da64b6',
 'd5f4ef8d3e5011ef9daa9cb6d0da64b6',
 'd5f4ef8e3e5011ef90489cb6d0da64b6',
 'd5f4ef8f3e5011ef96b59cb6d0da64b6',
 'd5f4ef903e5011ef95489cb6d0da64b6',
 'd5f4ef913e5011ef95959cb6d0da64b6',
 'd5f4ef923e5011ef99219cb6d0da64b6',
 'd5f4ef933e5011efb5829cb6d0da64b6',
 'd5f4ef943e5011efb68b9cb6d0da64b6',
 'd5f4ef953e5011ef98499cb6d0da64b6',
 'd5f4ef963e5011ef85ee9cb6d0da64b6',
 'd5f4ef973e5011efa6b79cb6d0da64b6',
 'd5f4ef983e5011efb1359cb6d0da64b6',
 'd5f4ef993e5011efb7069cb6d0da64b6',
 'd5f4ef9a3e5011ef92a19cb6d0da64b6',
 'd5f4ef9b3e5011efbd919cb6d0da64b6',
 'd5f4ef9c3e5011ef92bf9cb6d0da64b6',
 'd5f4ef9d3e5011efa02c9cb6d0da64b6',
 'd5f4ef9e3e5011ef91519cb6d0da64b6',
 'd5f4ef9f3e5011efb3489cb6d0da64b6',
 'd5f4efa03e5011ef88c69cb6d0da64b6',
 'd5f4efa13e5011efa3789cb6d0da64b6',
 'd5f4efa23e5011efa38a9cb6d0da64b6',
 'd5f4efa33e5011ef93d29cb6d0da64b6',
 'd5f4efa43e5011ef8fab9cb6d0da64b6',
 'd5f4efa53e5011ef99f99cb6d0da64b6',
 'd5f4efa63e5011efb1a79cb6d0da64b6',
 'd5f4efa73e5011ef9f019cb6d0da64b6',
 'd5f4efa83e5011efb4489cb6d0da64b6',
 'd5f4efa93e5011efb86b9cb6d0da64b6',
 'd5f4efaa3e5011ef87c29cb6d0da64b6',
 'd5f4efab3e5011ef98929cb6d0da64b6',
 'd5f4efac3e5011efbbe79cb6d0da64b6',
 'd5f4efad3e5011ef8a039cb6d0da64b6',
 'd5f4efae3e5011efa7d29cb6d0da64b6',
 'd5f4efaf3e5011ef95719cb6d0da64b6',
 'd5f4efb03e5011ef8e089cb6d0da64b6',
 'd5f4efb13e5011ef9bd69cb6d0da64b6',
 'd5f4efb23e5011efb8889cb6d0da64b6',
 'd5f4efb33e5011efb2999cb6d0da64b6',
 'd5f4efb43e5011ef8bb19cb6d0da64b6',
 'd5f4efb53e5011efbeae9cb6d0da64b6',
 'd5f4efb63e5011ef86489cb6d0da64b6',
 'd5f4efb73e5011efaf0e9cb6d0da64b6',
 'd5f4efb83e5011efa2359cb6d0da64b6',
 'd5f4efb93e5011ef8fcc9cb6d0da64b6',
 'd5f4efba3e5011ef86849cb6d0da64b6',
 'd5f4efbb3e5011efa72d9cb6d0da64b6',
 'd5f4efbc3e5011ef994c9cb6d0da64b6',
 'd5f4efbd3e5011ef95339cb6d0da64b6',
 'd5f4efbe3e5011ef99bc9cb6d0da64b6',
 'd5f4efbf3e5011ef9b0e9cb6d0da64b6',
 'd5f4efc03e5011ef9b059cb6d0da64b6',
 'd5f4efc13e5011ef91949cb6d0da64b6',
 'd5f4efc23e5011efb07e9cb6d0da64b6',
 'd5f4efc33e5011ef9eef9cb6d0da64b6',
 'd5f4efc43e5011efab6e9cb6d0da64b6',
 'd5f4efc53e5011efb8519cb6d0da64b6',
 'd5f4efc63e5011efb68e9cb6d0da64b6',
 'd5f4efc73e5011ef87af9cb6d0da64b6',
 'd5f4efc83e5011efacd09cb6d0da64b6',
 'd5f4efc93e5011ef9a8c9cb6d0da64b6',
 'd5f4efca3e5011ef97789cb6d0da64b6',
 'd5f4efcb3e5011ef976f9cb6d0da64b6',
 'd5f4efcc3e5011ef83ac9cb6d0da64b6',
 'd5f4efcd3e5011efacd09cb6d0da64b6',
 'd5f516a13e5011ef88069cb6d0da64b6',
 'd5f516a23e5011efa3079cb6d0da64b6',
 'd5f516a33e5011efab299cb6d0da64b6',
 'd5f516a43e5011ef88149cb6d0da64b6',
 'd5f516a53e5011efb4a79cb6d0da64b6',
 'd5f516a63e5011efb8b99cb6d0da64b6',
 'd5f516a73e5011ef90729cb6d0da64b6',
 'd5f516a83e5011ef80469cb6d0da64b6',
 'd5f516a93e5011ef98349cb6d0da64b6',
 'd5f516aa3e5011ef827e9cb6d0da64b6',
 'd5f516ab3e5011efbff69cb6d0da64b6',
 'd5f516ac3e5011ef83809cb6d0da64b6',
 'd5f516ad3e5011efbe019cb6d0da64b6',
 'd5f516ae3e5011efbe1c9cb6d0da64b6',
 'd5f516af3e5011ef999b9cb6d0da64b6',
 'd5f516b03e5011ef91579cb6d0da64b6',
 'd5f516b13e5011efbea69cb6d0da64b6',
 'd5f516b23e5011efbf889cb6d0da64b6',
 'd5f516b33e5011ef99e39cb6d0da64b6',
 'd5f516b43e5011ef90a39cb6d0da64b6',
 'd5f516b53e5011ef88de9cb6d0da64b6',
 'd5f516b63e5011efb5859cb6d0da64b6',
 'd5f516b73e5011efb5109cb6d0da64b6',
 'd5f516b83e5011efa6d79cb6d0da64b6',
 'd5f516b93e5011ef92179cb6d0da64b6',
 'd5f516ba3e5011efa38e9cb6d0da64b6',
 'd5f516bb3e5011efb71e9cb6d0da64b6',
 'd5f516bc3e5011efabaf9cb6d0da64b6',
 'd5f516bd3e5011ef9c429cb6d0da64b6',
 'd5f516be3e5011ef94349cb6d0da64b6',
 'd5f516bf3e5011ef82839cb6d0da64b6',
 'd5f516c03e5011efaae79cb6d0da64b6',
 'd5f516c13e5011efb53a9cb6d0da64b6',
 'd5f516c23e5011efbb889cb6d0da64b6',
 'd5f516c33e5011efac309cb6d0da64b6',
 'd5f516c43e5011efae5f9cb6d0da64b6',
 'd5f516c53e5011ef80309cb6d0da64b6',
 'd5f516c63e5011ef8a209cb6d0da64b6',
 'd5f516c73e5011ef90d39cb6d0da64b6',
 'd5f516c83e5011ef91f39cb6d0da64b6',
 'd5f516c93e5011efa2259cb6d0da64b6',
 'd5f516ca3e5011ef84449cb6d0da64b6']

## Transaction data

In [9]:
transaction_list=[]
customer_id_list = customer_df["customer_id"]

for i in range(100000):
    transaction_id = generate_random_id()
    customer_id = random.choice(customer_id_list)
    transaction_type = random.choice(["retrait", "dep√¥t", "transfert"])
    amount = uniform(100, 10000000)
    transaction_date = fake.date_between(start_date, end_date)
    location = fake.address()
    device_id = random.choice(device_id_list)
    status = random.choice(["√©chou√©e", "r√©ussie"])
    is_fraud = random.choice([0,1])

    transaction_dict = {
        "transaction_id": transaction_id,
        "customer_id": customer_id,
        "transaction_type": transaction_type,
        "amount": amount,
        "transaction_date": transaction_date,
        "location": location,
        "device_id": device_id,
        "status": status,
        "is_fraud": is_fraud
    }

    transaction_list.append(transaction_dict)

transaction_df = pd.DataFrame(transaction_list)
print(transaction_df.shape)
transaction_df.head()

(100000, 9)

,transaction_id,customer_id,transaction_type,amount,transaction_date,location,device_id,status,is_fraud
0,d5fafef53e5011ef8d159cb6d0da64b6,d32653013e5011efa7119cb6d0da64b6,retrait,5.979082e+06,2015-01-19,USCGC Thompson\nFPO AA 80425,d5f516c83e5011ef91f39cb6d0da64b6,r√©ussie,1
1,d5fafef63e5011ef8bbe9cb6d0da64b6,cc45ff523e5011ef89289cb6d0da64b6,dep√¥t,7.653624e+06,2018-03-18,"1878 Morgan Spurs Apt. 348\nSouth Kathyland, W...",d5f4efbc3e5011ef994c9cb6d0da64b6,√©chou√©e,0
2,d5fb26083e5011ef853b9cb6d0da64b6,d19813893e5011ef89ba9cb6d0da64b6,dep√¥t,4.298566e+06,2015-08-28,"1163 Ware Mountain\nLynnton, LA 70786",d5f4ef8c3e5011ef87d89cb6d0da64b6,√©chou√©e,0
3,d5fb4da43e5011efa8e69cb6d0da64b6,d075b9c53e5011ef80a29cb6d0da64b6,retrait,1.987565e+06,2014-04-24,"473 Davis Path\nPort Bryantown, VI 62789",d5f516ca3e5011ef84449cb6d0da64b6,r√©ussie,1
4,d5fb74a33e5011ef91c69cb6d0da64b6,d1c453f83e5011efbb779cb6d0da64b6,dep√¥t,3.221553e+06,2015-02-01,"43372 Robert Crescent\nNicoleview, OK 73399",d5f4a18e3e5011ef9ec89cb6d0da64b6,√©chou√©e,0

In [10]:
transaction_df.to_csv('../tables/transactions.csv')

## Transaction history data

In [11]:
transaction_history_list = []

for i, transaction in transaction_df.iterrows():
    history_id = generate_random_id()
    customer_id = transaction.customer_id
    transaction_id = transaction.transaction_id
    previous_balance = transaction.amount + uniform(0, 10000000)

    if transaction.transaction_type == "dep√¥t":
        new_balance = previous_balance + transaction.amount
    else:
        new_balance = previous_balance - transaction.amount
        
    transaction_date = transaction.transaction_date

    transaction_history_dict = {
        "history_id" : history_id,
        "customer_id" : customer_id,
        "transaction_id" : transaction_id,
        "previous_balance" : previous_balance,
        "new_balance" : new_balance,
        "transaction_date": transaction_date
    }
    transaction_history_list.append(transaction_history_dict)

transaction_history_df = pd.DataFrame(transaction_history_list)
print(transaction_history_df.shape)
transaction_history_df.head()

(100000, 6)

,history_id,customer_id,transaction_id,previous_balance,new_balance,transaction_date
0,05a38e913e5111efb5db9cb6d0da64b6,d32653013e5011efa7119cb6d0da64b6,d5fafef53e5011ef8d159cb6d0da64b6,7.722516e+06,1.743434e+06,2015-01-19
1,05a38e923e5111ef9a379cb6d0da64b6,cc45ff523e5011ef89289cb6d0da64b6,d5fafef63e5011ef8bbe9cb6d0da64b6,1.741836e+07,2.507198e+07,2018-03-18
2,05a3b5393e5111ef9c2b9cb6d0da64b6,d19813893e5011ef89ba9cb6d0da64b6,d5fb26083e5011ef853b9cb6d0da64b6,5.945690e+06,1.024426e+07,2015-08-28
3,05a3b53a3e5111efb2d39cb6d0da64b6,d075b9c53e5011ef80a29cb6d0da64b6,d5fb4da43e5011efa8e69cb6d0da64b6,5.818349e+06,3.830784e+06,2014-04-24
4,05a3b53b3e5111efa0a09cb6d0da64b6,d1c453f83e5011efbb779cb6d0da64b6,d5fb74a33e5011ef91c69cb6d0da64b6,1.190797e+07,1.512952e+07,2015-02-01

In [12]:
transaction_history_df.to_csv('../tables/transaction_history.csv')

## Transaction pattern data

## alerts data

## fraude_cases data

## regions data